### ISSUE TITLE
Sugestia

### ISSUE THREAD

**Issue by kacperleague9** [Lukasz825700516/CameraKeybinds#1]
Siemka, fajny mod!
Dodasz może opcje Hold, ktora dziala tylko jak przytrzymujesz i wraca to poprzedniego?
Jeszcze third peson freecam bylby kozak! jak w tych smiesznych klientach!

**Comment by Lukasz825700516** [comment]
Hej
Pomysł z przytrzymywaniem klawisza jest fajny, pojawi się w najnowszym updacie na 1.16.5 (czy jaka to teraz najnowsza wersja, nie będąca snapshotem xd)
Freecam będzie nową funkcjonalnością/trybem kamery, a ta modyfikacja skupia się tylko na ułatwianiu zmieniania typów kamer.

**Comment by kacperleague9** [comment]
Ta nowa aktualizacja buguje się, jak jestem w first person i przytrzymam third person tak z 1 sekunde lub wiecej to juz nie wraca z powrotem

**Comment by Lukasz825700516** [comment]
Naprawione, jak jednak ten bug nadal się pojawiał, to pod #2 wołaj.
